version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15572

  mongodb:
    image: mongo:4.0.10
    container_name: mongodb
    ports:
      - 27017:27017

  mias-rest-gate:
    build:
      context: ../mias-rest-gate/
      dockerfile: docker/Dockerfile
    container_name: mias-rest-gate
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      RABBIT_HOST: rabbitmq
    links:
      - rabbitmq

  mias-core:
    build:
      context: ../mias-core/
      dockerfile: docker/Dockerfile
    container_name: mias-core
    ports:
      - 8082:8082
    environment:
      SERVER_PORT: 8082
      DB_HOST: mongodb
      RABBIT_HOST: rabbitmq
    links:
      - mongodb
      - rabbitmq
